[project]
name = "fish-pond"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bleak>=2.0.0",
    "websockets>=15.0.1",
]
